# Generated by Django 3.1.1 on 2020-09-17 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tasks')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('sort_index', models.PositiveIntegerField(verbose_name='Sorted')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'board cards',
                'verbose_name_plural': 'board card',
                'db_table': 'Board_Card',
            },
        ),
        migrations.CreateModel(
            name='BoardUserExecutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boardcards', verbose_name='Tasks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'board user executor',
                'verbose_name_plural': 'board user executors',
                'db_table': 'Board_user_executors',
            },
        ),
        migrations.CreateModel(
            name='BoardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(verbose_name='Do you owner')),
                ('is_readonly', models.BooleanField(verbose_name='Read only')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boards', verbose_name='Board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'board users',
                'verbose_name_plural': 'board user',
                'db_table': 'Board_User',
            },
        ),
        migrations.CreateModel(
            name='BoardColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Name Column')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sort_index', models.PositiveIntegerField(verbose_name='Sorted')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boards', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'board columns',
                'verbose_name_plural': 'board column',
                'db_table': 'Board_Column',
            },
        ),
        migrations.AddField(
            model_name='boardcards',
            name='board_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boardcolumns', verbose_name='Name Column'),
        ),
        migrations.AddField(
            model_name='boardcards',
            name='board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boards', verbose_name='Board'),
        ),
        migrations.CreateModel(
            name='BoardCardComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, verbose_name='Message')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.boardcards', verbose_name='Tasks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'board card comment',
                'verbose_name_plural': 'board card comments',
                'db_table': 'Board_card_comments',
            },
        ),
    ]
