# Generated by Django 3.1.1 on 2020-09-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20200917_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcards',
            name='board_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.boardcolumns', verbose_name='Name Column'),
        ),
        migrations.AlterField(
            model_name='boardcards',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Task'),
        ),
    ]
